# Generated by Django 4.2.7 on 2024-01-02 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cocktail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('primary_spirit', models.CharField(max_length=255)),
                ('root_cocktail', models.CharField(max_length=255)),
                ('recipe', models.TextField()),
            ],
        ),
    ]
