# Generated by Django 4.2.7 on 2023-12-05 22:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_alter_blogpost_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="last_updated",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="date",
            field=models.DateTimeField(),
        ),
    ]
