# Generated by Django 4.2.7 on 2023-11-14 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='color',
            field=models.CharField(default='red', max_length=50),
        ),
    ]
