# Generated by Django 4.2.7 on 2023-11-21 21:37

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_question_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='color2',
            field=colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=25, samples=None),
        ),
    ]
